### ISSUE TITLE
Runtime error while running

### ISSUE THREAD

**Issue by hellcoderz** [OmerShapira/Syntactic#14]
java -jar target/syntactic-1.0-SNAPSHOT.jar big data/plaintext/ output 10 50 0.1
Syntactic, Build 53
****************/home/coderz/soft/Syntactic/output/big 06.07.2013 22-55-56 created
big : Included /home/coderz/soft/Syntactic/data/plaintext/big.txt
Building Database

---

.Done building database

Words: 2
Rare words: 2
Words to scan: 0

<pre>
Exception in thread "main" java.util.NoSuchElementException
    at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1113)
    at java.util.TreeMap$KeyIterator.next(TreeMap.java:1169)
    at syntaxLearner.Learner.prepareClusters(Learner.java:80)
    at syntaxLearner.Learner.clusterCommonWords(Learner.java:182)
    at syntaxLearner.Learner.learn(Learner.java:417)
    at syntaxLearner.LearnerMain.testCorpus(LearnerMain.java:38)
    at syntaxLearner.LearnerMain.main(LearnerMain.java:15)
</pre>

**Comment by hellcoderz** [comment]
The input file was in wrong format.
